[package]
name = "infag"
version = "0.1.0"
edition = "2021"

[dependencies]
maud = "0.26.0"
poem = "3.0.0"
serde = { version = "1.0.197", features = ["derive"] }
tokio = { version = "1.37.0", features = ["rt"] }
